/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package inicioSesion;

import com.google.cloud.firestore.Firestore;
import static inicioSesion.RegistroSesion.getSHA256;
import java.awt.Color;
import javax.swing.JOptionPane;
import utils.UtilsAnimales;

/**
 *
 * @author Aaron
 */
public class InicioSesion extends javax.swing.JDialog {

    /**
     * Creates new form InicioSesion
     */
    private Firestore firestore;
    private boolean continuar;
    
    public InicioSesion(java.awt.Frame parent, boolean modal, Firestore firestore) {
        super(parent, modal);
        initComponents();
        iniciarSesion.putClientProperty( "JButton.buttonType", "roundRect" );
        user.putClientProperty( "JComponent.roundRect", true );
        passwd.putClientProperty( "JComponent.roundRect", true );
        this.firestore = firestore;
        this.continuar = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        passwd = new javax.swing.JPasswordField();
        iniciarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 350));

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButton.setText("X");
        exitButton.setOpaque(true);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, 30));

        user.setText("Usuario");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 270, 40));

        passwd.setText("jPasswordField1");
        passwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwdMouseClicked(evt);
            }
        });
        jPanel1.add(passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 270, 40));

        iniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        iniciarSesion.setText("Iniciar sesion");
        iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 140, 50));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enka");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 270, 130));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setBackground(new Color(255,134, 134));
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        exitButton.setBackground(new Color(255,0, 0));
    }//GEN-LAST:event_exitButtonMouseExited

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        user.setText("");
    }//GEN-LAST:event_userMouseClicked

    private void passwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwdMouseClicked
        passwd.setText("");
    }//GEN-LAST:event_passwdMouseClicked

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionActionPerformed
        System.out.println("Hola");
        UtilsAnimales util = new UtilsAnimales(firestore);
        String[] credenciales = util.getAdmin();
        char[] contraseña = passwd.getPassword();
        String passwdT = "";
        for(int i = 0; i < contraseña.length; i++){
            passwdT += i;
        }
        passwdT = getSHA256(passwdT);
        if(credenciales[1].equals(passwdT) && user.getText().equals(credenciales[0])){
            continuar = true;
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Credenciales erroneos, intentelo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_iniciarSesionActionPerformed
    
    
    /**
     * @param args the command line arguments
     */

    public boolean isContinuar() {
        return continuar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitButton;
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
