/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package correo;

import com.google.cloud.firestore.Firestore;
import javax.swing.JOptionPane;
import utils.UtilsCorreo;

/**
 *
 * @author Aaron
 */
public class PnlAjustesCorreo extends javax.swing.JPanel {

    /**
     * Creates new form PnlAjustesCorreo
     */
    
    private Firestore firestore;
    
    public PnlAjustesCorreo(Firestore firestore) {
        initComponents();
        UtilsCorreo util = new UtilsCorreo(firestore);
        servidor.setText(util.getServidorSmtp());
        puerto.setText(util.getPuertoSmtp());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        servidor = new javax.swing.JTextField();
        editarServidorSmtp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        puerto = new javax.swing.JTextField();
        editarPuertoSmtp = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(150, 409));
        jPanel1.setLayout(new java.awt.GridLayout(10, 1));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Servidor smtp:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Puerto:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("TLS:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel3);

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.GridLayout(10, 1));

        servidor.setEditable(false);
        servidor.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        servidor.setPreferredSize(new java.awt.Dimension(300, 34));
        jPanel3.add(servidor);

        editarServidorSmtp.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        editarServidorSmtp.setText("Editar");
        editarServidorSmtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarServidorSmtpActionPerformed(evt);
            }
        });
        jPanel3.add(editarServidorSmtp);

        jPanel2.add(jPanel3);

        puerto.setEditable(false);
        puerto.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        puerto.setPreferredSize(new java.awt.Dimension(300, 34));
        jPanel4.add(puerto);

        editarPuertoSmtp.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        editarPuertoSmtp.setText("Editar");
        editarPuertoSmtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPuertoSmtpActionPerformed(evt);
            }
        });
        jPanel4.add(editarPuertoSmtp);

        jPanel2.add(jPanel4);

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TLSv1.2");
        jPanel5.add(jLabel4);

        jPanel2.add(jPanel5);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void editarServidorSmtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarServidorSmtpActionPerformed
        if(editarServidorSmtp.getText().equals("Editar")){
            servidor.setEditable(true);
            editarServidorSmtp.setText("Continuar");
        }else{
            UtilsCorreo util = new UtilsCorreo(firestore);
            if(!(servidor.getText().isEmpty() || servidor.getText().isBlank())){
                util.updateServidorSmtp(servidor.getText());
            }else{
                JOptionPane.showMessageDialog(null, "Nuevo servidor vacio", "Aviso", 2);
            }
            editarServidorSmtp.setText("Editar");
            servidor.setEditable(false);
        }
    }//GEN-LAST:event_editarServidorSmtpActionPerformed

    private void editarPuertoSmtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPuertoSmtpActionPerformed
        if(editarPuertoSmtp.getText().equals("Editar")){
            puerto.setEditable(true);
            editarPuertoSmtp.setText("Continuar");
        }else{
            UtilsCorreo util = new UtilsCorreo(firestore);
            if(!(puerto.getText().isEmpty() || puerto.getText().isBlank())){
                util.updatePuertoSmtp(puerto.getText());
            }else{
                JOptionPane.showMessageDialog(null, "Nuevo puerto vacio", "Aviso", 2);
            }
            editarPuertoSmtp.setText("Editar");
            puerto.setEditable(false);
        }
    }//GEN-LAST:event_editarPuertoSmtpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarPuertoSmtp;
    private javax.swing.JButton editarServidorSmtp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField puerto;
    private javax.swing.JTextField servidor;
    // End of variables declaration//GEN-END:variables
}
